<?php
// Prevent direct access to this file
if (!defined('ABSPATH')) {
    exit;
}

function aiseo_add_internal_links_to_all_posts() {
    global $wpdb;

    // Get all posts generated by our plugin, including drafts
    $posts = $wpdb->get_results("
        SELECT p.ID, p.post_title, p.post_content 
        FROM {$wpdb->posts} p
        JOIN {$wpdb->postmeta} pm ON p.ID = pm.post_id
        WHERE pm.meta_key = '_aiseo_generated'
        AND p.post_status IN ('publish', 'draft')
    ");

    aiseo_log("SQL Query for fetching posts: " . $wpdb->last_query);
    aiseo_log("Number of posts fetched for internal linking: " . count($posts));

    // Get all keywords and their associated post IDs
    $keyword_posts = $wpdb->get_results("
        SELECT post_id, meta_value as keyword
        FROM {$wpdb->postmeta}
        WHERE meta_key = '_aiseo_primary_keyword'
    ");
    $keyword_map = array_column($keyword_posts, 'post_id', 'keyword');

    aiseo_log("Starting to process " . count($posts) . " posts for internal linking");

    aiseo_log("SQL Query for fetching posts: " . $wpdb->last_query);
    aiseo_log("Number of posts fetched for internal linking: " . count($posts));

    aiseo_log("SQL Query for fetching keywords: " . $wpdb->last_query);
    aiseo_log("Number of keywords fetched: " . count($keyword_posts));

    foreach ($posts as $post) {
        $updated_content = $post->post_content;
        $links_added = 0;
        $max_links = 5; // Maximum number of links to add per post

        // Get all keywords
        $keywords = wp_get_object_terms($post->ID, 'aiseo_keyword', array('fields' => 'names'));

        foreach ($keywords as $keyword) {
            if ($links_added >= $max_links) {
                break;
            }

            // Skip if this is the primary keyword for the current post
            if (get_post_meta($post->ID, '_aiseo_primary_keyword', true) === $keyword) {
                continue;
            }

            // Find the post associated with this keyword
            $keyword_post_id = isset($keyword_map[$keyword]) ? $keyword_map[$keyword] : null;

            if ($keyword_post_id && $keyword_post_id != $post->ID) {
                $link_url = get_permalink($keyword_post_id);

                // Use preg_replace to add the link, ensuring we don't link within existing links or headings
                $pattern = '/(?<!<a[^>]*>)(?<!<h[1-6]>)' . preg_quote($keyword, '/') . '(?![^<]*<\/a>)(?![^<]*<\/h[1-6]>)/i';
                $replacement = '<a href="' . esc_url($link_url) . '">' . $keyword . '</a>';
                $new_content = preg_replace($pattern, $replacement, $updated_content, 1);

                if ($new_content !== $updated_content) {
                    $updated_content = $new_content;
                    $links_added++;
                    aiseo_log("Added internal link for keyword '{$keyword}' in post ID: {$post->ID}");
                }
            }
        }
        aiseo_log("Original content length for post ID {$post->ID}: " . strlen($post->post_content));
        aiseo_log("Updated content length for post ID {$post->ID}: " . strlen($updated_content));

        if ($updated_content !== $post->post_content) {
            $post_data = get_post($post->ID, ARRAY_A);
            $post_data['post_content'] = $updated_content;
            
            wp_update_post($post_data);
            
            aiseo_log("Updated post ID: {$post->ID} with {$links_added} internal links");
        }
    }

    aiseo_log("Completed processing " . count($posts) . " posts for internal linking");
    aiseo_log("Internal linking process completed for all posts.");
}

function aiseo_add_internal_links_to_post($post_id) {
    global $wpdb;

    $post = get_post($post_id);
    if (!$post) {
        return array('status' => 'error', 'message' => 'Post not found.');
    }

    $updated_content = $post->post_content;
    $links_added = 0;
    $max_links = 5; // Maximum number of links to add per post

    // Get all keywords and their associated post IDs
    $keyword_posts = $wpdb->get_results("
        SELECT post_id, meta_value as keyword
        FROM {$wpdb->postmeta}
        WHERE meta_key = '_aiseo_primary_keyword'
    ");
    $keyword_map = array_column($keyword_posts, 'post_id', 'keyword');

    // Get all keywords for this post
    $keywords = wp_get_object_terms($post_id, 'aiseo_keyword', array('fields' => 'names'));

    foreach ($keywords as $keyword) {
        if ($links_added >= $max_links) {
            break;
        }

        // Skip if this is the primary keyword for the current post
        if (get_post_meta($post_id, '_aiseo_primary_keyword', true) === $keyword) {
            continue;
        }

        // Find the post associated with this keyword
        $keyword_post_id = isset($keyword_map[$keyword]) ? $keyword_map[$keyword] : null;

        if ($keyword_post_id && $keyword_post_id != $post_id) {
            $link_url = get_permalink($keyword_post_id);

            // Use preg_replace to add the link, ensuring we don't link within existing links or headings
            $pattern = '/(?<!<a[^>]*>)(?<!<h[1-6]>)' . preg_quote($keyword, '/') . '(?![^<]*<\/a>)(?![^<]*<\/h[1-6]>)/i';
            $replacement = '<a href="' . esc_url($link_url) . '">' . $keyword . '</a>';
            $new_content = preg_replace($pattern, $replacement, $updated_content, 1);

            if ($new_content !== $updated_content) {
                $updated_content = $new_content;
                $links_added++;
                aiseo_log("Added internal link for keyword '{$keyword}' in post ID: {$post_id}");
            }
        }
    }

    if ($updated_content !== $post->post_content) {
        $post_data = get_post($post_id, ARRAY_A);
        $post_data['post_content'] = $updated_content;
        
        wp_update_post($post_data);
        
        aiseo_log("Updated post ID: {$post_id} with {$links_added} internal links");
        aiseo_log("Original content length: " . strlen($post->post_content));
        aiseo_log("Updated content length: " . strlen($updated_content));
        
        return array(
            'status' => 'success',
            'message' => "Added {$links_added} internal links to the post.",
            'content' => $updated_content
        );
    } else {
        return array(
            'status' => 'info',
            'message' => 'No new internal links were added to the post.'
        );
    }
}